In [1]:
import numpy as np
from scipy import signal
import fft_util as fft_util

## 1-D convolution using 1-D FFT

In [2]:
"""
test the built-in 1-D conv
"""
x = np.array([1, 2, 3], dtype=float)
y = np.array([5, -1, -9, 0, 1, 2, 6, 8, 12, 1], dtype=float)
def test_builtin_conv():    
    conv_result = np.convolve(y, x, "full")
    print(conv_result.tolist())
    

In [3]:
if False:
    test_builtin_conv()
    x = np.array([1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=float)
    fftx = np.fft.fft(x)
    print fftx.tolist()
    y = np.array([5, -1, -9, 0, 1, 2, 6, 8, 12, 1, 0, 0], dtype=float)
    ffty = np.fft.fft(y)
    print ffty.tolist()
    x_conv_y = np.round(np.fft.ifft(fftx * ffty).real)
    print x_conv_y.tolist()

In [4]:
if True:
    x = [1, 5, 6, 8, 9]
    y = [0, 1, 8, -2, -5]
    output_length = fft_util.find_ceil_power_of_two(len(x) + len(y) - 1)
    # we need to zero padding first, very important
    x_array = np.array(fft_util.zero_padding(x, output_length))
    y_array = np.array(fft_util.zero_padding(y, output_length))
    conv_result = np.convolve(x_array, y_array, "full")
    conv_fft_result = np.fft.ifft(np.fft.fft(x_array) * np.fft.fft(y_array)).real
    print "conv result: " , conv_result.tolist()
    print "fft conv result: ", np.round(conv_fft_result).tolist()

conv result:  [0, 1, 13, 44, 41, 36, 26, -58, -45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
fft conv result:  [0.0, 1.0, 13.0, 44.0, 41.0, 36.0, 26.0, -58.0, -45.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


## 2D-convolution using 2D-FFT

In [5]:
h = (np.random.rand(3, 3) - 0.5) * 20   # renormalize to zero-center and have a maximum of 20
print h, h.shape

[[ 8.14974137  4.19353344 -0.27159095]
 [ 4.46791534  5.51554533 -1.90353686]
 [-4.78522894  1.05596624 -1.12456604]] (3, 3)


In [6]:
x = (np.random.rand(32, 32) - 0.5) * 20

In [7]:
conv_result = signal.convolve2d(x, h)
print conv_result.shape

(34, 34)


In [8]:
h_pad = np.lib.pad(h, ((0, 31), (0, 31)), 'constant', constant_values=(0))
print h_pad.shape

(34, 34)


In [9]:
x_pad = np.lib.pad(x, ((0, 2), (0, 2)), 'constant', constant_values=(0))
print x_pad.shape

(34, 34)


In [10]:
h_fft2 = np.fft.fft2(h_pad)
x_fft2 = np.fft.fft2(x_pad)
conv_fft2_result = np.fft.ifft2(h_fft2 * x_fft2)

In [11]:
print sum(sum(np.round(conv_fft2_result.real - conv_result)))

0.0


In [14]:
x = (np.random.rand(1, 8) - 0.5) * 20
my_fft_result = fft_util.eight_point_fft(sum(x.tolist(), []))
built_in_fft_result = np.fft.fft(x).tolist()
print "my:", my_fft_result
print "built-in:", built_in_fft_result

my: [(11.24171300485628+0j), (-12.680551171048009+0.26016975067935433j), (-17.694916622645348+7.448622807717534j), (-3.935265957982158+3.322812041113948j), (-16.585898421483265+0j), (-3.935265957982158-3.3228120411139477j), (-17.694916622645348-7.448622807717534j), (-12.680551171048009-0.260169750679355j)]
built-in: [[(11.24171300485628+0j), (-12.68055117104801+0.2601697506793572j), (-17.694916622645348+7.448622807717534j), (-3.935265957982157+3.322812041113945j), (-16.585898421483265+0j), (-3.9352659579821587-3.3228120411139503j), (-17.694916622645348-7.448622807717534j), (-12.680551171048005-0.2601697506793519j)]]
